name: Build Flutter APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Project Structure
        run: flutter create . --platforms android --namespace com.filt.app # Specifichiamo il namespace qui

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build APK
        # Usiamo un flag per ignorare i problemi di versioni Gradle minori se necessario
        run: flutter build apk --release --no-tree-shake-icons
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FiltApp-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
