name: Build Flutter APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Project Structure
        # Aggiungiamo il flag --androidx per risolvere il problema del vecchio Registrar
        run: |
          flutter create . --platforms android --namespace com.filt.app --androidx
          cd android
          echo "android.useAndroidX=true" >> gradlew.properties
          echo "android.enableJetifier=true" >> gradlew.properties

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build APK
        # Aggiungiamo un flag per gestire eventuali icone mancanti e forzare la compilazione
        run: flutter build apk --release --no-tree-shake-icons --no-pub
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FiltApp-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
